sudo: false
language: cpp
compiler: gcc

# Need GCC 5 and Boost 1.54+, which aren't in the 12.04 repositories - install
# from PPAs.
addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - libboost-filesystem1.55-dev
      - gcc-5
      - g++-5


before_script:
  # Use GCC 5.
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  # Build Google Test
  - cd ..
  - wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz -O - | tar -xz
  - cd googletest-release-1.7.0
  - cmake .
  - make
  # Move back into the cloned LOOT repo path.
  - cd $TRAVIS_BUILD_DIR
  - mkdir build && cd build
  # Fetch plugins to test with.
  - wget https://github.com/WrinklyNinja/testing-plugins/archive/master.tar.gz -O - | tar -xz
  - mv testing-plugins-master/* ./
  # Travis machines are 64 bit, and the dependencies use dynamic linking.
  - cmake .. -DGTEST_ROOT=../googletest-release-1.7.0

script: make tests && ./tests
